### PR TITLE
added storage tutorial

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Review by thempel — COMMENTED** [review]
Looks pretty cool! In terms of user experience, I have two comments:
1. Would it be possible to print a human-readable time format in `pyemma_list_models`? This lengthy expression is a bit difficult to interpret.
2. It's a bit suboptimal to have a model named 'latest' if it's not actually the latest one saved. Especially for people who don't read this tutorial, it will almost certainly cause confusion and subsequent github issues. What about adding something like `#1` to latest and increase the counter (as done by gromacs), if people just want to dump models?

Technical remarks:
1. Doesn't h5py need to be added to the list of requirements for pyEMMA?
2. Just a remark: Executing bash commands does only work if users are taking the same conda environment for starting their ipython notebook server and the notebook itself. Or at least the server environment must have the latest pyemma version to have this command available. 
3. The function `pyemma.list_models` hasn't been merged into the devel branch yet so I couldn't test it ;-)

**Review by clonker — CHANGES_REQUESTED** [review]
- Agreed on the time format in `pyemma_list_models`, this should be changed.
- "latest" model: Instead of latest#1... I personally would opt for making the model name mandatory, then everything is explicit. Makes the API a but clunkier of course.. One could also think about naming it "default".
- Wrt the technical remark about the bash command: As long as the command is somehow available - i think it should be version-agnostic as it only depends on the internal hdf5 group/dataset tree which probably won't change any time soon - I guess

**Comment by marscher** [comment]
Thanks for having a look at this guys. The date format changes are already PRed in PyEMMA. I like the idea of incrementing model names, using always "latest" is indeed confusing. However I imagine that it is hard to disentangle automatically generated names, when one wants to restore things (okay I have 50 models named 1-50 in my file, what is what).
So going for an explicit name seems to be a better option.

The bash command is part of the installation, so it belongs to the version of PyEMMA being imported.

**Review by clonker — APPROVED** [review]

**Comment by marscher** [comment]
Thanks!

**Review by thempel — APPROVED** [review]

**Pull request merged**
